[package]
name = "zed-1"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
colored = "3.0.0"
gpui = "0.2.2"
serde = "1.0.228"
serde_json = "1.0.145"
reqwest = { version = "0.12", features = ["blocking", "json"] }
rayon = "1.10"
